<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $events = [
            // Organization 1 - Segítő Kezek Alapítvány (5 esemény)
            [
                'organization_id' => 1,
                'title' => 'Adománygyűjtés a rászorulók számára',
                'description' => 'Közös adománygyűjtés a szociálisan hátrányos helyzetű családok megsegítésére.',
                'location' => 'Budapest, Városliget',
                'date' => now()->addDays(7)->setHour(10)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 1,
                'title' => 'Mentális egészség workshop',
                'description' => 'Interaktív workshop a mentális egészség és wellbeing témájában.',
                'location' => 'Budapest, Erkel Szálló',
                'date' => now()->addDays(14)->setHour(14)->setMinute(30),
                'status' => 'Függőben',
                'capacity' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 1,
                'title' => 'Szociális támogatási szeminár',
                'description' => 'Hogyan lehet hatékonyan segíteni a rászoruló családoknak.',
                'location' => 'Budapest, Pesti Vigadó',
                'date' => now()->addDays(21)->setHour(11)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 1,
                'title' => 'Karácsonyváró adománygyűjtés',
                'description' => 'Karácsonyi ajándékgyűjtés a szegény családok gyerekeihez.',
                'location' => 'Budapest, V. kerület',
                'date' => now()->addDays(35)->setHour(16)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 1,
                'title' => 'Önkéntes toborzás és képzés',
                'description' => 'Új önkéntesek toborzása és alapvetô képzése.',
                'location' => 'Budapest, Városháza',
                'date' => now()->addDays(28)->setHour(13)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Organization 2 - Közösségi Fejlesztés Szövetség (5 esemény)
            [
                'organization_id' => 2,
                'title' => 'Közösségi nap a városban',
                'description' => 'Szórakoztató és informatív közösségi rendezvény a helyi közösség erősítésére.',
                'location' => 'Debrecen, Nagyerdő',
                'date' => now()->addDays(10)->setHour(11)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 2,
                'title' => 'Önkéntes kiképzés',
                'description' => 'Alapvető képzés az önkéntesek számára, hogy hatékonyan tudjanak segíteni.',
                'location' => 'Debrecen, Önkéntes Központ',
                'date' => now()->addDays(21)->setHour(9)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 2,
                'title' => 'Közösségi kert projekt indítása',
                'description' => 'Közös kertépítés a város zöldítésére és közösségépítésre.',
                'location' => 'Debrecen, Nagyerdei Park',
                'date' => now()->addDays(15)->setHour(10)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 2,
                'title' => 'Szomszédság építő piac',
                'description' => 'Helyi termelôk és kézművesek vására.',
                'location' => 'Debrecen, Északi Pályaudvar',
                'date' => now()->addDays(18)->setHour(8)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 2,
                'title' => 'Közösségi tárház fejlesztési fórum',
                'description' => 'Szabad dolgok megosztásának erôsítése a közösségben.',
                'location' => 'Debrecen, Közösségi Ház',
                'date' => now()->addDays(25)->setHour(14)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Organization 3 - Ifjúsági Mentorálási Alapítvány (5 esemény)
            [
                'organization_id' => 3,
                'title' => 'Fiatalok karrierfóruma',
                'description' => 'Pályaválasztási tanácsadás és karrierépítési tippek fiatalok számára.',
                'location' => 'Szeged, Szegedi Tudományegyetem',
                'date' => now()->addDays(8)->setHour(15)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 3,
                'title' => 'Mentorálási program záróeseménye',
                'description' => 'A mentorálási program végeredménye és az elért sikerek bemutatása.',
                'location' => 'Szeged, Móra Ferenc Könyvtár',
                'date' => now()->addDays(28)->setHour(18)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 3,
                'title' => 'Digitális készségek workshop',
                'description' => 'Programozás és digitális eszközök alapjai fiatalok számára.',
                'location' => 'Szeged, Technológiai Központ',
                'date' => now()->addDays(12)->setHour(16)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 3,
                'title' => 'Mentor-mentorált párosítási esemény',
                'description' => 'Új mentor-mentorált párok megismerkedésének rendezvénye.',
                'location' => 'Szeged, Egyetem Klubja',
                'date' => now()->addDays(5)->setHour(17)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 3,
                'title' => 'Leadership és személyiségfejlesztés tréning',
                'description' => 'Vezetési készségek fejlesztése fiataloknak.',
                'location' => 'Szeged, Business Hub',
                'date' => now()->addDays(32)->setHour(10)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Organization 4 - Egészséges Élet Szövetsége (5 esemény)
            [
                'organization_id' => 4,
                'title' => 'Futóversenyen keresztül a jó egészségért',
                'description' => 'Szórakoztató futóverseny az egészséges életmód népszerűsítésére.',
                'location' => 'Pécs, Mecsek alja',
                'date' => now()->addDays(12)->setHour(8)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 4,
                'title' => 'Fitness és nutrició előadás',
                'description' => 'Szakértő előadás az egészséges táplálkozásról és fitnesz trendekről.',
                'location' => 'Pécs, Egészség Központ',
                'date' => now()->addDays(5)->setHour(17)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 4,
                'title' => 'Jóga és meditáció kezdőknek',
                'description' => 'Relaxációs és wellness foglalkozás.',
                'location' => 'Pécs, Wellnes Centrum',
                'date' => now()->addDays(9)->setHour(18)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 4,
                'title' => 'Egészséges életmód expo',
                'description' => 'Vállalatoknak és egyéneknek bemutatkozási lehetôség.',
                'location' => 'Pécs, Messze-Völgyi Sportcsarnok',
                'date' => now()->addDays(22)->setHour(10)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 4,
                'title' => 'Koronavírus utáni rehabilitáció workshop',
                'description' => 'Egészségügyi tanácsadás a covid utáni felépüléshez.',
                'location' => 'Pécs, Egészségügyi Egyetem',
                'date' => now()->addDays(30)->setHour(14)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Organization 5 - Fenntarthatóság Szövetsége (5 esemény)
            [
                'organization_id' => 5,
                'title' => 'Fenntartható célok megvalósításáért szeminár',
                'description' => 'Tudnivalók a fenntartható fejlődési célokról és azok megvalósításáról.',
                'location' => 'Győr, Városi Könyvtár',
                'date' => now()->addDays(15)->setHour(10)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 5,
                'title' => 'Zöld akció nap',
                'description' => 'Közös sétálás és környezetvédelmi tevékenységek a természet védelméért.',
                'location' => 'Győr, Rábapark',
                'date' => now()->addDays(20)->setHour(9)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 5,
                'title' => 'Hulladékmentes élet - gyakorlati tippek',
                'description' => 'Hogyan csökkentsük a hulladéktermelésünket?',
                'location' => 'Győr, Ökológiai Központ',
                'date' => now()->addDays(11)->setHour(16)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 5,
                'title' => 'Közös biketrip a Rábáig',
                'description' => 'Kerékpáros túra a fenntartható közlekedés népszerûsítéséhez.',
                'location' => 'Győr, Rába Völgy',
                'date' => now()->addDays(17)->setHour(8)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organization_id' => 5,
                'title' => 'Fenntartható Fashion Show',
                'description' => 'Ökológikus ruhadesignerek és divatmárkák bemutatása.',
                'location' => 'Győr, Kulturális Központ',
                'date' => now()->addDays(26)->setHour(18)->setMinute(0),
                'status' => 'Függőben',
                'capacity' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('events')->insert($events);
    }
}
